DROP DATABASE IF EXISTS JAVAFINALTEST; 
CREATE DATABASE IF NOT EXISTS JAVAFINALTEST;
USE JAVAFINALTEST;

-- Tạo bảng 
CREATE TABLE `USER`(
	USERID		MEDIUMINT AUTO_INCREMENT,
	FIRSTNAME	VARCHAR(20),
    LASTNAME	VARCHAR(20),
    EMAIL		VARCHAR(254) UNIQUE,
    PHONE		CHAR(10) UNIQUE,
    `PASSWORD`	VARCHAR(12),
    `ROLE`		ENUM ('MANAGER', 'EMPLOYEE'),
    PRIMARY KEY (USERID)
);

CREATE TABLE MANAGER(
	USERID		MEDIUMINT AUTO_INCREMENT,
    ExpInYear	SMALLINT,
    PRIMARY KEY (USERID)
);

CREATE TABLE EMPLOYEE(
	USERID		MEDIUMINT AUTO_INCREMENT,
    PROJECTNAME VARCHAR(30) DEFAULT 'Have not enjoy yet',
    PROSKILL	VARCHAR(50),
    PRIMARY KEY (USERID)
);

-- FOREIGN KEY
ALTER TABLE MANAGER 
   ADD FOREIGN KEY (USERID) REFERENCES `USER` (USERID) ON DELETE CASCADE;
   
ALTER TABLE EMPLOYEE 
   ADD FOREIGN KEY (USERID) REFERENCES `USER` (USERID) ON DELETE CASCADE;

/*SELECT * FROM `USER`;
SELECT * FROM EMPLOYEE;
SELECT * FROM MANAGER;*/